twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    strict_variables: false
    globals:
        swiperTimer: 5000
        association: '@App\Service\GlobalAssociation'

when@test:
    twig:
        strict_variables: true
