vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        band_picture:
            uri_prefix: "/uploads/images/band"
            upload_destination: '%upload_directory%images/band/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer