---
deployment:
  tasks:
    - export DEPLOYPATH=/home/brle7172/repositories/panelproduction.fr
    - composer install --no-dev --optimize-autoloader
    - php bin/console doctrine:migrations:migrate --no-interaction --env=prod
    - php bin/console ckeditor:install --tag=4.22.1
    - yarn install --frozen-lockfile
    - yarn encore production
    - php bin/console assets:install public --symlink --relative --env=prod
    - php bin/console cache:clear --env=prod --no-warmup
    - php bin/console cache:warmup --env=prod